services:
  - type: web
    name: nectar-reviews-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_VERSION
        value: 2026-07
