const express = require('express');
const { Review, Settings, ModuleStatus } = require('../models');
const { cleanText, clampNumber, cleanShopDomain } = require('../utils/validation');
const { signPayload, hashToken } = require('../utils/reviewTokens');
const { ReviewToken } = require('../models');
const router = express.Router();

function shop(req) { return req.shopDomain || cleanShopDomain(req.query.shopDomain || req.body?.shopDomain || ''); }

router.get('/me', (req, res) => res.json({ ok: true, shopDomain: shop(req) }));
router.get('/settings', async (req, res, next) => { try { const shopDomain = shop(req); const settings = await Settings.findOneAndUpdate({ shopDomain }, { $setOnInsert: { shopDomain } }, { new: true, upsert: true }); res.json({ ok: true, settings }); } catch (e) { next(e); } });
router.patch('/settings', async (req, res, next) => { try { const shopDomain = shop(req); const settings = await Settings.findOneAndUpdate({ shopDomain }, { $set: req.body || {}, $setOnInsert: { shopDomain } }, { new: true, upsert: true }); res.json({ ok: true, settings }); } catch (e) { next(e); } });

router.get('/reviews', async (req, res, next) => { try { const q = { shopDomain: shop(req), isDeleted: { $ne: true } }; if (req.query.status) q.status = cleanText(req.query.status, 20); const reviews = await Review.find(q).sort({ createdAt: -1 }).limit(Number(req.query.limit || 100)).lean(); res.json({ ok: true, reviews }); } catch (e) { next(e); } });
router.patch('/reviews/:id', async (req, res, next) => { try { const allowed = ['status','headline','comment','verifiedPurchase','verificationNote','isDeleted','deletedAt']; const set = {}; for (const key of allowed) if (key in req.body) set[key] = req.body[key]; if (set.isDeleted && !set.deletedAt) set.deletedAt = new Date(); const review = await Review.findOneAndUpdate({ _id: req.params.id, shopDomain: shop(req) }, { $set: set }, { new: true }); if (!review) return res.status(404).json({ error: 'Review not found' }); res.json({ ok: true, review }); } catch (e) { next(e); } });
router.post('/reviews/import', async (req, res, next) => { try { const shopDomain = shop(req); const rows = Array.isArray(req.body?.reviews) ? req.body.reviews : []; const docs = rows.slice(0, 1000).map(row => ({ shopDomain, itemId: cleanText(row.itemId || row.productId || '__site__', 240), reviewScope: row.reviewScope === 'site' ? 'site' : 'product', userId: cleanText(row.userId || row.name || 'Imported customer', 120), rating: clampNumber(row.rating, 1, 5, 5), headline: cleanText(row.headline || row.title, 180), comment: cleanText(row.comment || row.body, 5000), status: cleanText(row.status || 'accepted', 20), source: 'import', sourcePlatform: cleanText(row.sourcePlatform || 'manual', 80), sourceLabel: cleanText(row.sourceLabel || 'Manual import', 120), verifiedPurchase: Boolean(row.verifiedPurchase), externalReviewId: cleanText(row.externalReviewId || '', 180), importedAt: new Date() })); const inserted = docs.length ? await Review.insertMany(docs, { ordered: false }) : []; res.json({ ok: true, inserted: inserted.length }); } catch (e) { next(e); } });

router.get('/dashboard', async (req, res, next) => { try { const shopDomain = shop(req); const [total, accepted, pending, site] = await Promise.all([Review.countDocuments({ shopDomain }), Review.countDocuments({ shopDomain, status: 'accepted' }), Review.countDocuments({ shopDomain, status: 'pending' }), Review.countDocuments({ shopDomain, reviewScope: 'site' })]); res.json({ ok: true, metrics: { total, accepted, pending, site } }); } catch (e) { next(e); } });
router.get('/modules/status', async (req, res, next) => { try { const shopDomain = shop(req); const modules = await ModuleStatus.find({ shopDomain }).lean(); const defaults = ['reviews','messaging','loyalty','discounts','cart-rewards','migration-centre'].map(moduleKey => ({ moduleKey, enabled: true, live: moduleKey === 'reviews' })); res.json({ ok: true, modules: modules.length ? modules : defaults }); } catch (e) { next(e); } });
router.patch('/modules/status/:moduleKey', async (req, res, next) => { try { const shopDomain = shop(req); const module = await ModuleStatus.findOneAndUpdate({ shopDomain, moduleKey: req.params.moduleKey }, { $set: { enabled: req.body.enabled !== false, live: Boolean(req.body.live), config: req.body.config || {} } }, { new: true, upsert: true }); res.json({ ok: true, module }); } catch (e) { next(e); } });

router.post('/review-links', async (req, res, next) => { try { const shopDomain = shop(req); const payload = { shopDomain, orderId: cleanText(req.body.orderId, 120), email: cleanText(req.body.email, 320), itemIds: Array.isArray(req.body.itemIds) ? req.body.itemIds.map(v => cleanText(v, 240)) : [], exp: Date.now() + 1000 * 60 * 60 * 24 * 30 }; const token = signPayload(payload); await ReviewToken.create({ shopDomain, tokenHash: hashToken(token), orderId: payload.orderId, email: payload.email, itemIds: payload.itemIds, expiresAt: new Date(payload.exp) }); res.json({ ok: true, token, url: `${process.env.APP_URL || ''}/pages/review?token=${encodeURIComponent(token)}` }); } catch (e) { next(e); } });

module.exports = router;
