const express = require('express');
const { getProgram, updateProgram, addLedgerEntry, getCustomerState } = require('../modules/loyalty/loyalty.service');
const { cleanText } = require('../utils/validation');
const router = express.Router();
router.get('/program', async (req, res, next) => { try { res.json({ ok: true, program: await getProgram(req.shopDomain) }); } catch(e){ next(e); } });
router.patch('/program', async (req, res, next) => { try { res.json({ ok: true, program: await updateProgram(req.shopDomain, req.body || {}) }); } catch(e){ next(e); } });
router.get('/customers/:customerRef', async (req, res, next) => { try { res.json({ ok: true, state: await getCustomerState(req.shopDomain, cleanText(req.params.customerRef, 240)) }); } catch(e){ next(e); } });
router.post('/ledger', async (req, res, next) => { try { res.json({ ok: true, entry: await addLedgerEntry(req.shopDomain, req.body || {}) }); } catch(e){ next(e); } });
module.exports = router;
