const { cleanUrl } = require('../utils/safe');
const { supplierDefaultsForUrl } = require('./supplierProfile.service');
function xmlLocs(xml=''){return Array.from(String(xml).matchAll(/<loc>\s*([^<]+)\s*<\/loc>/gi)).map(m=>m[1].trim());}
function productUrl(url=''){try{return /\/products\/[^/?#]+\/?$/.test(new URL(url).pathname);}catch(_){return false;}}
async function fetchText(url,timeoutMs=15000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{headers:{'User-Agent':'ELEV8 Product Importer/1.0','Accept':'application/xml,text/xml,text/html,application/json;q=0.9,*/*;q=0.8'},redirect:'follow',signal:controller.signal});if(!response.ok)throw new Error(`Discovery fetch failed ${response.status} for ${url}`);return await response.text();}finally{clearTimeout(timer);}}
async function discoverFromSitemap(rootUrl,maxProducts=500){const root=new URL(rootUrl);const main=await fetchText(`${root.origin}/sitemap.xml`);const locs=xmlLocs(main);const direct=locs.filter(productUrl);const childMaps=locs.filter(url=>/sitemap.*\.xml/i.test(url));const products=[...direct];for(const mapUrl of childMaps){if(products.length>=maxProducts)break;if(!/product/i.test(mapUrl)&&childMaps.some(x=>/product/i.test(x)))continue;try{const xml=await fetchText(mapUrl);for(const url of xmlLocs(xml)){if(productUrl(url))products.push(url);if(products.length>=maxProducts)break;}}catch(error){console.warn('[site-import] sitemap child skipped:',mapUrl,error.message);}}return Array.from(new Set(products)).slice(0,maxProducts);}
async function discoverShopifyProductsJson(rootUrl,maxProducts=500){const root=new URL(rootUrl);const urls=[];let page=1;while(urls.length<maxProducts&&page<=10){let json;try{json=JSON.parse(await fetchText(`${root.origin}/products.json?limit=250&page=${page}`));}catch(_){break;}const products=Array.isArray(json.products)?json.products:[];if(!products.length)break;for(const product of products){if(product.handle)urls.push(`${root.origin}/products/${product.handle}`);if(urls.length>=maxProducts)break;}if(products.length<250)break;page+=1;}return Array.from(new Set(urls)).slice(0,maxProducts);}
async function discoverSiteProducts({rootUrl,maxProducts=500}){const safe=cleanUrl(rootUrl);if(!safe)throw new Error('A valid supplier website URL is required.');let urls=[],method='';try{urls=await discoverFromSitemap(safe,maxProducts);method='sitemap';}catch(error){console.warn('[site-import] sitemap discovery failed:',error.message);}if(!urls.length){urls=await discoverShopifyProductsJson(safe,maxProducts);method='shopify-products-json';}if(!urls.length)throw new Error('No product URLs could be discovered from this site.');return {rootUrl:safe,method,urls,count:urls.length,supplierDefaults:supplierDefaultsForUrl(safe)};}
module.exports={discoverSiteProducts,discoverFromSitemap,discoverShopifyProductsJson};
