name = "Nectar cart reward discount"
type = "function"
uid = "nectar-cart-reward-discount"
api_version = "2026-07"

[[extensions.targeting]]
target = "cart.lines.discounts.generate.run"
input_query = "src/run.graphql"
export = "run"

[extensions.build]
command = "cargo build --target=wasm32-wasi --release"
path = "target/wasm32-wasi/release/nectar_cart_reward_discount_function.wasm"
