name = "Nectar loyalty redemption"
type = "ui_extension"
uid = "nectar-loyalty-redemption"
api_version = "2026-07"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.settings]
[[extensions.settings.fields]]
key = "app_url"
type = "single_line_text_field"
name = "App URL"

[[extensions.settings.fields]]
key = "shop_domain"
type = "single_line_text_field"
name = "Shop domain"
