query RunInput {
  cart {
    lines {
      id
      quantity
      attribute(key: "_nectar_reward") {
        value
      }
      campaignId: attribute(key: "_nectar_campaign_id") {
        value
      }
      tierId: attribute(key: "_nectar_tier_id") {
        value
      }
      rewardId: attribute(key: "_nectar_reward_id") {
        value
      }
      claimToken: attribute(key: "_nectar_claim_token") {
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
        }
      }
    }
  }
  discount {
    metafield(namespace: "$app:nectar-cart-rewards", key: "function-config") {
      value
    }
  }
}
