query RunInput {
  cart {
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product { id }
        }
      }
      attribute(key: "_nectar_reward") { value }
      claimToken: attribute(key: "_nectar_claim_token") { value }
      campaignId: attribute(key: "_nectar_campaign_id") { value }
      tierId: attribute(key: "_nectar_tier_id") { value }
    }
  }
  discountNode {
    metafield(namespace: "nectar", key: "cart_reward_config") { value }
  }
}
